#!/usr/bin/env python3
"""Generate src/unicode_tables.h from Python's unicodedata.

Output: general-category classes (L, M, N), canonical combining classes,
canonical decompositions and primary compositions for NFC.
Usage: python3 tools/gen_unicode_tables.py > src/unicode_tables.h
"""
import sys
import unicodedata as ud

MAX = 0x110000
HANGUL = range(0xAC00, 0xD7A4)


def ranges(values):
    """Collapse per-code-point values into (start, end, value) runs, dropping 0."""
    out, start, prev = [], None, 0
    for cp in range(MAX + 1):
        value = values(cp) if cp < MAX else 0
        if value != prev:
            if prev:
                out.append((start, cp - 1, prev))
            start, prev = cp, value
    return out


def cls(cp):
    cat = ud.category(chr(cp))
    return {"L": 1, "M": 2, "N": 4}.get(cat[0], 0)


def canonical(cp):
    d = ud.decomposition(chr(cp))
    if not d or d.startswith("<") or cp in HANGUL:
        return None
    return [int(x, 16) for x in d.split()]


def main():
    w = sys.stdout.write
    w("/* Generated by tools/gen_unicode_tables.py from Python unicodedata %s. Do not edit. */\n"
      % ud.unidata_version)
    w("#define UC_TABLE_VERSION \"%s\"\n" % ud.unidata_version)

    cat = ranges(cls)
    w("static const uint32_t UC_CLASS[][3] = {\n")
    for s, e, v in cat:
        w("  {0x%X,0x%X,%d},\n" % (s, e, v))
    w("};\n")

    ccc = ranges(lambda cp: ud.combining(chr(cp)))
    w("static const uint32_t UC_CCC[][3] = {\n")
    for s, e, v in ccc:
        w("  {0x%X,0x%X,%d},\n" % (s, e, v))
    w("};\n")

    decomp, comp = [], []
    for cp in range(MAX):
        d = canonical(cp)
        if d is None:
            continue
        decomp.append((cp, d[0], d[1] if len(d) > 1 else 0))
        if len(d) == 2 and ud.normalize("NFC", chr(cp)) == chr(cp):
            comp.append((d[0], d[1], cp))
    w("static const uint32_t UC_DECOMP[][3] = {\n")
    for c, a, b in decomp:
        w("  {0x%X,0x%X,0x%X},\n" % (c, a, b))
    w("};\n")
    comp.sort()
    w("static const uint32_t UC_COMPOSE[][3] = {\n")
    for a, b, c in comp:
        w("  {0x%X,0x%X,0x%X},\n" % (a, b, c))
    w("};\n")


if __name__ == "__main__":
    main()
