module TransformerShapes

// Index arithmetic of the Clean Room Transformer (SPEC.md 4.1, 4.2, 4.5),
// checked over every configuration in the bounded integer scope.
// Real checkpoint shapes are checked by EngineShapes (generated by
// tools/check_formal.py from the engine's own weight table).

// ---------------------------------------------------------------- head sharing

// A layout with `many` heads sharing `few` heads is valid when `few` divides `many`.
pred Grouped[many, few: Int] {
  many > 0 and few > 0 and rem[many, few] = 0
}

// Head j of `many` reads shared head j / (many / few). The engine uses this
// for query heads -> KV heads (GQA) and for DeltaNet value heads -> key heads.
fun shared[j, many, few: Int]: Int { div[j, div[many, few]] }

assert SharedHeadInRange {
  all many, few, j: Int |
    (Grouped[many, few] and j >= 0 and j < many) implies
      (shared[j, many, few] >= 0 and shared[j, many, few] < few)
}

// Every shared head serves exactly many/few heads.
assert SharedHeadBalanced {
  all many, few, k: Int |
    (Grouped[many, few] and k >= 0 and k < few) implies
      #{ j: Int | j >= 0 and j < many and shared[j, many, few] = k } = div[many, few]
}

// Heads sharing one head are consecutive (repeat_interleave, not tiling).
assert SharedHeadContiguous {
  all many, few, j: Int |
    (Grouped[many, few] and j >= 0 and j < minus[many, 1]) implies
      shared[j, many, few] <= shared[plus[j, 1], many, few]
}

// Tiling (j mod few) would be a different model: a witness where the two differ.
pred TilingDiffers[many, few, j: Int] {
  Grouped[many, few] and few > 1 and div[many, few] > 1
  j >= 0 and j < many
  shared[j, many, few] != rem[j, few]
}

// -------------------------------------------------------------------- RoPE

// Rotary dims pair d with d + rot/2 (half-split layout), rot even, rot <= hd.
pred RopeLayout[rot, hd: Int] { rot > 0 and rem[rot, 2] = 0 and rot <= hd }

fun partner[d, rot: Int]: Int {
  (d < div[rot, 2]) => plus[d, div[rot, 2]] else minus[d, div[rot, 2]]
}

assert RopePairsAreAnInvolution {
  all rot, hd, d: Int |
    (RopeLayout[rot, hd] and d >= 0 and d < rot) implies
      (partner[d, rot] >= 0 and partner[d, rot] < rot and
       partner[d, rot] != d and partner[partner[d, rot], rot] = d)
}

// ------------------------------------------------------- DeltaNet conv split

// The conv output of width C = 2*Dk + Dv splits into q [0, Dk), k [Dk, 2Dk), v [2Dk, C).
fun segment[i, dk, dv: Int]: Int {
  (i < dk) => 0 else ((i < mul[2, dk]) => 1 else 2)
}

assert ConvSplitIsAPartition {
  all dk, dv, i: Int |
    (dk > 0 and dv > 0 and i >= 0 and i < plus[mul[2, dk], dv]) implies
      (segment[i, dk, dv] = 0 and i < dk) or
      (segment[i, dk, dv] = 1 and i >= dk and i < mul[2, dk]) or
      (segment[i, dk, dv] = 2 and i >= mul[2, dk])
}

check SharedHeadInRange for 7 Int
check SharedHeadBalanced for 6 Int
check SharedHeadContiguous for 7 Int
check RopePairsAreAnInvolution for 7 Int
check ConvSplitIsAPartition for 7 Int
run TilingDiffers for 6 Int
